import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
import {
  sasukeProfile,
  ghibliProfile,
  jujutsuKaisenProfile,
  itadoriProfile,
  hinataProfile,
  kakashiProfile,
  narutoProfile,
  fushiguroProfile,
  gojoProfile,
  jiraiyaProfile,
  sakuraProfile,
} from "./assets";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: "8c0aa5c2-864c-47d8-a490-e25cbae56be0",
    firstName: "Gojo",
    lastName: "Satoru",
    username: "oioioi_Satoru",
    password: "Gojoishandsome",
    createdAt: "2023-04-10T10:38:12+05:30",
    updatedAt: "2023-06-17T10:33:36+05:30",
    email: "gojo@jujutsu.high",
    profile: gojoProfile,
    portfolio: "https://vinit-kanse.netlify.app",
    bio: "Don't Worry, I'm The Strongest",
    followers: [
      {
        _id: "2c71b5c1-e6dd-4e6e-b072-c54cfe05db89",
        firstName: "Itadori",
        lastName: "Yuji",
        username: "not_just_sukunas_vessel",
        profile: itadoriProfile,
      },
    ],
    following: [
      {
        _id: "2c71b5c1-e6dd-4e6e-b072-c54cfe05db89",
        firstName: "Itadori",
        lastName: "Yuji",
        username: "not_just_sukunas_vessel",
        profile:
          "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2023/01/yuji-itadori-weilding-cursed-energy-1.jpg",
      },
    ],
    bookmarks: [],
  },
  {
    _id: "2c71b5c1-e6dd-4e6e-b072-c54cfe05db89",
    firstName: "Itadori",
    lastName: "Yuji",
    username: "not_just_sukunas_vessel",
    password: "megumi123",
    createdAt: "2023-05-11T10:12:12+05:30",
    updatedAt: "2023-06-16T18:11:07+05:30",
    email: "yujihere@jujutsu.tech",
    profile: itadoriProfile,
    portfolio: "https://isha.netlify.app",
    bio: "I am more than just sukuna's vessel",
    followers: [
      {
        _id: "fe3029a4-9591-4435-879e-bccdac5b45e6",
        firstName: "Fushiguro",
        lastName: "Megumi",
        username: "megumi.fushiguro",
        profile: fushiguroProfile,
      },
    ],
    following: [],
    bookmarks: [],
  },
  {
    _id: "fe3029a4-9591-4435-879e-bccdac5b45e6",
    firstName: "Fushiguro",
    lastName: "Megumi",
    username: "megumi.fushiguro",
    password: "1234",
    createdAt: "2023-06-25T10:38:12+05:30",
    updatedAt: "2023-07-10T10:33:36+05:30",
    email: "fushguro@jujutsu.tech",
    profile: fushiguroProfile,
    link: "https://vinit-kanse.netlify.app",
    bio: "Divine Dogs…. Go and Feast!",
    followers: [],
    following: [],
    bookmarks: [],
  },
  {
    _id: "8c0aa5c2-864c-47d8-a490-e25cbae56be0-90s",
    firstName: "Naruto",
    lastName: "Uzumaki",
    username: "dattebayo_naruto",
    password: "ShadowCloneJutsu",
    createdAt: "2023-06-19T09:00:00+05:30",
    updatedAt: "2023-06-19T09:00:00+05:30",
    email: "naruto@konoha.village",
    profile: narutoProfile,
    portfolio: "https://example.com/naruto-portfolio",
    bio: "Believe it!",
    followers: [
      {
        _id: "2c71b5c1-e6dd-4e6e-b072-c54cfe05db89",
        firstName: "Sasuke",
        lastName: "Uchiha",
        username: "the_la(o)st_uchiha_sasuke",
        profile: sasukeProfile,
      },
    ],
    following: [
      {
        _id: "2c71b5c1-e6dd-4e6e-b072-c54cfe05db89",
        firstName: "Sasuke",
        lastName: "Uchiha",
        username: "the_la(o)st_uchiha_sasuke",
        profile: sasukeProfile,
      },
    ],
    bookmarks: [],
  },
  {
    _id: "3f1d4f4a-55a6-45f9-97df-eeaf39983f8d-er4",
    firstName: "Jujutsu",
    lastName: "Kaisen",
    username: "Jujutsu_Kaisen_",
    password: "Sharingan123",
    createdAt: "2023-06-19T10:00:00+05:30",
    updatedAt: "2023-06-19T10:00:00+05:30",
    email: "jujutsu@kaisen.tech",
    profile: jujutsuKaisenProfile,
    portfolio: "https://example.com/kakashi-portfolio",
    bio: "Those who break the rules are scum, but those who abandon their friends are worse than scum.",
    followers: [
      {
        _id: "8c0aa5c2-864c-47d8-a490-e25cbae56be0-90s",
        firstName: "Naruto",
        lastName: "Uzumaki",
        username: "dattebayo_naruto",
        profile: narutoProfile,
      },
    ],
    following: [
      {
        _id: "8c0aa5c2-864c-47d8-a490-e25cbae56be0-90s",
        firstName: "Naruto",
        lastName: "Uzumaki",
        username: "dattebayo_naruto",
        profile: narutoProfile,
      },
    ],
    bookmarks: [],
  },
  {
    _id: "3f1d4f4a-55a6-45f9-97df-eeaf39983f8d",
    firstName: "Kakashi",
    lastName: "Hatake",
    username: "copyninja_kakashi",
    password: "Sharingan123",
    createdAt: "2023-06-19T10:00:00+05:30",
    updatedAt: "2023-06-19T10:00:00+05:30",
    email: "kakashi@konoha.village",
    profile: kakashiProfile,
    portfolio: "https://example.com/kakashi-portfolio",
    bio: "Those who break the rules are scum, but those who abandon their friends are worse than scum.",
    followers: [
      {
        _id: "8c0aa5c2-864c-47d8-a490-e25cbae56be0-90s",
        firstName: "Naruto",
        lastName: "Uzumaki",
        username: "dattebayo_naruto",
        profile: narutoProfile,
      },
    ],
    following: [
      {
        _id: "8c0aa5c2-864c-47d8-a490-e25cbae56be0-90s",
        firstName: "Naruto",
        lastName: "Uzumaki",
        username: "dattebayo_naruto",
        profile: narutoProfile,
      },
    ],
    bookmarks: [],
  },
  {
    _id: "4b3d8b1d-d5f5-4d9a-bd0f-8f6949d3a28d-ert5",
    username: "ghiblipicture",
    firstName: "Studio",
    lastName: "Ghibli",
    password: "studioGhibli",
    createdAt: "2023-06-19T11:00:00+05:30",
    updatedAt: "2023-06-19T11:00:00+05:30",
    email: "studioghibli@tokyo.tech",
    profile: ghibliProfile,
    portfolio: "https://example.com/sasuke-portfolio",
    bio: "Creating Experiences",
    followers: [
      {
        _id: "8c0aa5c2-864c-47d8-a490-e25cbae56be0-90s",
        firstName: "Naruto",
        lastName: "Uzumaki",
        username: "dattebayo_naruto",
        profile: narutoProfile,
      },
    ],
    following: [
      {
        _id: "8c0aa5c2-864c-47d8-a490-e25cbae56be0-90s",
        firstName: "Naruto",
        lastName: "Uzumaki",
        username: "dattebayo_naruto",
        profile: narutoProfile,
      },
    ],
    bookmarks: [],
  },
  {
    _id: "4b3d8b1d-d5f5-4d9a-bd0f-8f6949d3a28d",
    firstName: "Sasuke",
    lastName: "Uchiha",
    username: "the_la(o)st_uchiha_sasuke",
    password: "Avenger321",
    createdAt: "2023-06-19T11:00:00+05:30",
    updatedAt: "2023-06-19T11:00:00+05:30",
    email: "sasuke@konoha.village",
    profile: sasukeProfile,
    portfolio: "https://example.com/sasuke-portfolio",
    bio: "I'll become Hokage and change the village.",
    followers: [
      {
        _id: "8c0aa5c2-864c-47d8-a490-e25cbae56be0-90s",
        firstName: "Naruto",
        lastName: "Uzumaki",
        username: "dattebayo_naruto",
        profile: narutoProfile,
      },
    ],
    following: [
      {
        _id: "8c0aa5c2-864c-47d8-a490-e25cbae56be0-90s",
        firstName: "Naruto",
        lastName: "Uzumaki",
        username: "dattebayo_naruto",
        profile: narutoProfile,
      },
    ],
    bookmarks: [],
  },
  {
    _id: "f889e2f4-b2bb-4b2e-b76b-5d7c4fc5bb35",
    firstName: "Sakura",
    lastName: "Haruno",
    username: "cherryblossom_sakura",
    password: "MedicalNinja123",
    createdAt: "2023-06-19T12:00:00+05:30",
    updatedAt: "2023-06-19T12:00:00+05:30",
    email: "sakura@konoha.village",
    profile: sakuraProfile,
    portfolio: "https://example.com/sakura-portfolio",
    bio: "I won't let you harm my friends!",
    followers: [
      {
        _id: "8c0aa5c2-864c-47d8-a490-e25cbae56be0-90s",
        firstName: "Naruto",
        lastName: "Uzumaki",
        username: "dattebayo_naruto",
        profile: narutoProfile,
      },
      {
        _id: "4b3d8b1d-d5f5-4d9a-bd0f-8f6949d3a28d",
        firstName: "Sasuke",
        lastName: "Uchiha",
        username: "the_la(o)st_uchiha_sasuke",
        profile: sasukeProfile,
      },
    ],
    following: [
      {
        _id: "4b3d8b1d-d5f5-4d9a-bd0f-8f6949d3a28d",
        firstName: "Sasuke",
        lastName: "Uchiha",
        username: "the_la(o)st_uchiha_sasuke",
        profile: sasukeProfile,
      },
    ],
    bookmarks: [],
  },
  {
    _id: "6eaf64a2-6f53-4a5e-9e47-1961a87f3690",
    firstName: "Jiraiya",
    lastName: "",
    username: "toad_sannin",
    password: "PervySage321",
    createdAt: "2023-06-19T13:00:00+05:30",
    updatedAt: "2023-06-19T13:00:00+05:30",
    email: "jiraiya@hidden.leaf",
    profile: jiraiyaProfile,
    portfolio: "https://example.com/jiraiya-portfolio",
    bio: "I'll create a thousand jutsu that are more powerful than the Rasengan!",
    followers: [],
    following: [],
    bookmarks: [],
  },
  {
    _id: "72a8bca5-1340-4084-a91a-ec508ac7de7f",
    firstName: "Hinata",
    lastName: "Hyuga",
    username: "hyuga_hinata",
    password: "Byakugan123",
    createdAt: "2023-06-19T14:00:00+05:30",
    updatedAt: "2023-06-19T14:00:00+05:30",
    email: "hinata@hidden.leaf",
    profile: hinataProfile,
    portfolio: "https://example.com/hinata-portfolio",
    bio: "I'll always protect Naruto-kun!",
    followers: [
      {
        _id: "4b3d8b1d-d5f5-4d9a-bd0f-8f6949d3a28d",
        firstName: "Sasuke",
        lastName: "Uchiha",
        username: "the_la(o)st_uchiha_sasuke",
        profile: sasukeProfile,
      },
    ],
    following: [
      {
        _id: "4b3d8b1d-d5f5-4d9a-bd0f-8f6949d3a28d",
        firstName: "Sasuke",
        lastName: "Uchiha",
        username: "the_la(o)st_uchiha_sasuke",
        profile: sasukeProfile,
      },
    ],
    bookmarks: [],
  },
];
